--- #YAML:1.0
name:               Unicode-Stringprep
version:            1.01
abstract:           Preparation of Internationalized Strings (RFC 3454)
author:
    - Claus Faerber <CFAERBER@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:                5.006
    Unicode::Normalize:  0.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    perl:  5.008003
